const assert=require('node:assert/strict');
const {build}=require('../../frontend/underwriting-report.js');
const findings=[{finding_id:'a',material_id:'1',category:'agriculture_environment',detection_status:'detected'},{finding_id:'b',material_id:'1',category:'flammable_material',detection_status:'detected'},{finding_id:'c',material_id:'2',category:'agriculture_environment',detection_status:'uncertain'},{finding_id:'d',material_id:'3',category:'agriculture_environment',detection_status:'detected'},{finding_id:'e',material_id:'1',category:'installation_type',detection_status:'detected'}];
const result=build({findings,material_reviews:[{material_id:'1',finding_ids:['a','b','e'],action:'recommend_reject',triggered_rule_ids:['ENV-EXCLUDED-001'],missing_requirements:['补拍通道']},{material_id:'2',finding_ids:['c'],missing_requirements:['补拍通道']}],decision:{missing_requirements:['补拍通道','补充坐标']}});
assert.deepEqual(result.decisive.map(f=>f.finding_id),['a'],'Rejecting material must not turn every finding into a rejection basis');
assert.deepEqual(result.pending.map(f=>f.finding_id),['c'],'Uncertainty remains even when another image detects the same environment');
assert.deepEqual(result.risks.map(f=>f.finding_id),['b','d'],'An unreferenced detected environment is not a rule-confirmed rejection basis');
assert.deepEqual(result.observations.map(f=>f.finding_id),['e']);
assert.equal(result.tasks.length,2);assert.deepEqual(result.tasks[0].materials,['1','2'],'Merged requests retain all material references');
assert.equal(build({}).decisive.length,0);
console.log('6 report aggregation checks passed');
const {screeningData}=require('../../frontend/underwriting-report.js');
const old=screeningData({catastrophe_assessment:{expected_loss_risk:'high'},component_profile:{wind_load_pa:300},weather_profile:{historical_max_wind_m_s:30}});
assert.equal(old.legacy,true);
assert.equal(old.rows[0].capacity,300);
assert.equal(old.rows[0].ratio,null,'Historical results must not be recomputed using current thresholds');
assert.equal(old.rows[0].status,'not_saved');
const fresh=screeningData({catastrophe_assessment:{comparisons:[{hazard:'wind',capacity:300,event:30,demand:551.7,ratio:.544,status:'calculated',risk:'critical'}]}});
assert.equal(fresh.legacy,false);assert.equal(fresh.calculated,1);
assert.equal(fresh.rows[0].ratio,.544,'Use persisted server calculation without reconstructing it');
assert.equal(screeningData({}).rows[0].status,'not_evaluated');
console.log('Persisted screening and historical compatibility checks passed');
