'use strict';
PvWorkbench.init('risk');
const $=id=>document.getElementById(id), labels={wind:'风灾',hail:'雹灾',snow:'雪灾'}, risks={low:'余量充足',medium:'余量有限',high:'能力不足',critical:'明显不足',unknown:'无法判断'};
const map={windCapacity:['component','wind_load_pa'],hailCapacity:['component','hail_resistance_mm'],snowCapacity:['component','snow_load_pa'],windEvent:['weather','historical_max_wind_m_s'],hailEvent:['weather','historical_max_hail_mm'],snowEvent:['weather','historical_max_snow_load_pa']};
const storeKey='pv-risk-lab-v1';let sourceContext=null,contextToken=null;let config,mode='real',base={component:null,weather:null},original=null,records=[],current=null,busy=false;
const el=(tag,text,cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
function notice(text,error=false){$('notice').textContent=text;$('notice').className='notice'+(error?' error':'');}
async function api(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||data));return data;}
function number(id){const value=$(id).value.trim();if(!value)return null;const n=Number(value);if(!Number.isFinite(n)||!$(id).checkValidity())throw Error('请检查“'+$(id).parentElement.textContent.trim()+'”的数值范围');return n;}
function fill(){for(const [id,[part,key]] of Object.entries(map))$(id).value=base[part]?.[key]??'';$('model').value=base.component?.component_model||'';$('longitude').value=base.weather?.longitude??'';$('latitude').value=base.weather?.latitude??'';$('start').value=base.weather?.observation_start||'';$('end').value=base.weather?.observation_end||'';sources();}
function sources(){for(const part of ['component','weather']){const target=$(part+'Source');target.replaceChildren();const p=base[part];if(!p){target.textContent=part==='component'?'尚未取得组件参数；静态正背面载荷不会自动当作风、雪荷载。':'尚未取得气象数据；降雪量不会自动转换为雪荷载。';continue;}target.append(el('div',p.source_name||'手动测试参数'));if(p.source_url&&/^https?:\/\//.test(p.source_url)){const a=el('a','查看来源');a.href=p.source_url;a.target='_blank';a.rel='noopener';target.append(a);}if(part==='component'){target.append(el('div','型号：'+p.component_model));if(p.front_static_load_pa!=null)target.append(el('div',`静态载荷参考：正面 ${p.front_static_load_pa} Pa / 背面 ${p.back_static_load_pa??'缺失'} Pa（不参与风雪换算）`));}else{target.append(el('div',`查询位置：${p.longitude}, ${p.latitude}；时间：${p.observation_start||'未提供'} 至 ${p.observation_end||'未提供'}`));if(p.historical_max_daily_snowfall_cm!=null)target.append(el('div','历史单日降雪 '+p.historical_max_daily_snowfall_cm+' cm，仅供气候背景参考'));}target.append(el('div','取得时间：'+(p.retrieved_at?new Date(p.retrieved_at).toLocaleString('zh-CN'):'未提供')));}}
function controls(){const editable=mode==='simulated'||$('override').checked;for(const id of [...Object.keys(map),'critical','adequate'])$(id).readOnly=!editable;$('scenarios').hidden=mode!=='simulated';$('real').setAttribute('aria-pressed',String(mode==='real'));$('simulated').setAttribute('aria-pressed',String(mode==='simulated'));for(const b of document.querySelectorAll('button'))b.disabled=busy;$('export').disabled=busy||!current;for(const input of document.querySelectorAll('input,select'))input.disabled=busy;}
function draft(){return Object.fromEntries([...document.querySelectorAll('input,#scenario')].map(n=>[n.id,n.type==='checkbox'?n.checked:n.value]));}
function save(){try{localStorage.setItem(storeKey,JSON.stringify({sourceContext,contextToken,base,original,records,current,mode,dirty:!$('dirty').hidden,draft:draft()}));return true;}catch(e){notice('结果仍显示，但本地保存失败；请导出测试记录。',true);return false;}}
function dirty(){if(current)$('dirty').hidden=false;save();}
function setMode(value){mode=value;controls();dirty();notice(mode==='simulated'?'手动场景测试：修改参数或载入场景。结果将标记为模拟。':'真实数据测试：缺少的参数保持为空；手动覆盖会标记为模拟。');}
async function task(action){if(busy)return;busy=true;controls();try{await action();save();}catch(e){notice(e.message||'请求失败，请重试；已有结果仍保留。',true);}finally{busy=false;controls();}}
function input(){const manual=mode==='simulated'||$('override').checked;const overrides=[];let component=base.component?structuredClone(base.component):null,weather=base.weather?structuredClone(base.weather):null;const now=new Date().toISOString();
if(manual){component=component||{component_model:$('model').value.trim()||'手动测试组件',source_name:'手动模拟参数',source_url:null,retrieved_at:now,match_confidence:0};weather=weather||{longitude:number('longitude')??0,latitude:number('latitude')??0,source_name:'手动模拟灾害指标',retrieved_at:now};}
if(!manual&&component&&$('model').value.trim()!==component.component_model)throw Error('组件型号已修改，请重新查询参数。');
if(!manual&&weather&&(number('longitude')!==weather.longitude||number('latitude')!==weather.latitude||$('start').value!==(weather.observation_start||'')||$('end').value!==(weather.observation_end||'')))throw Error('位置或时间范围已修改，请重新查询历史气象。');
for(const [id,[part,key]] of Object.entries(map)){const target=part==='component'?component:weather;if(target){const value=number(id);if(value!=null&&part==='component'&&value<=0)throw Error('组件能力必须为正值；缺失时请留空。');if(value!==(base[part]?.[key]??null))overrides.push(key);target[key]=value;}}
if(manual&&component){component.component_model=$('model').value.trim()||'手动测试组件';if(component.component_model!==base.component?.component_model)overrides.push('component_model');}
if(manual&&weather){weather.longitude=number('longitude')??0;weather.latitude=number('latitude')??0;weather.observation_start=$('start').value||null;weather.observation_end=$('end').value||null;if(weather.longitude!==base.weather?.longitude||weather.latitude!==base.weather?.latitude)overrides.push('coordinates');}
return {mode,component,weather,overrides,adequate_margin_ratio:number('adequate'),critical_shortfall_ratio:number('critical')};}
const fmt=v=>v==null?'缺失':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:3});
function table(headers,rows){const t=document.createElement('table');const head=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=document.createElement('tbody');for(const row of rows){const r=document.createElement('tr');row.forEach(value=>r.append(el('td',String(value))));body.append(r);}t.append(body);return t;}
function result(record){current=record;const root=$('results');root.replaceChildren();$('dirty').hidden=true;$('resultMeta').textContent=new Date(record.created_at).toLocaleString('zh-CN')+' · 规则 '+record.rules_version;
const assessment=record.assessment,complete=record.comparisons.filter(r=>r.status==='calculated').length;const summary=el('div','','summary');summary.append(el('span',record.mode==='simulated'?'模拟测试 · 含手动参数或阈值':'真实数据测试','badge'+(record.mode==='simulated'?' bad':'')),el('h2',assessment.expected_loss_risk==='unknown'?'综合判断未完成':'综合筛查：'+risks[assessment.expected_loss_risk]),el('p',`${complete} / 3 项具备计算条件。${assessment.explanation}`),el('span',assessment.requires_manual_review?'需要人工复核':'当前规则未要求额外复核','muted'));root.append(summary);
const wrap=el('div','','tablewrap');wrap.append(table(['灾害','组件能力','历史指标','比较需求','能力比','本次判断'],record.comparisons.map(r=>[labels[r.hazard],fmt(r.capacity)+' '+r.unit,fmt(r.event)+' '+(r.hazard==='wind'?'m/s':r.unit),fmt(r.demand)+' '+r.unit,r.ratio==null?'—':r.ratio.toFixed(3),r.status==='insufficient'?'数据不足':risks[r.risk]])));root.append(wrap);const details=el('div','','pad');for(const row of record.comparisons){const d=el('details','','detail');d.append(el('summary',labels[row.hazard]+' · 查看计算过程与依据'));d.append(el('p',row.formula));if(row.status==='calculated')d.append(el('p',`${fmt(row.capacity)} ÷ ${fmt(row.demand)} = ${row.ratio==null?'没有正值需求，不计算比值':row.ratio.toFixed(5)}`));if(row.reason)d.append(el('p',row.reason));d.append(el('p',`分档：＜${assessment.critical_shortfall_ratio} 明显不足；＜1 能力不足；＜${assessment.adequate_margin_ratio} 余量有限；其余余量充足。`),el('p','触发规则：'+(row.rule_ids.join('、')||'该项未完成计算')));details.append(d);}if(record.input.overrides.length)details.append(el('p','手动覆盖字段：'+record.input.overrides.join('、'),'source'));const raw=el('details','','detail');raw.append(el('summary','输入快照、来源与结构化结果'),el('pre',JSON.stringify(record,null,2)));details.append(raw);root.append(details);controls();}
function histories(){const root=$('history');root.replaceChildren();for(const r of records){const b=el('button',new Date(r.created_at).toLocaleTimeString('zh-CN')+' · '+(r.mode==='simulated'?'模拟':'真实')+' · '+risks[r.assessment.expected_loss_risk]);b.onclick=()=>{sourceContext=r.source_context||null;PvWorkbench.contextBar(sourceContext);base={component:r.input.component,weather:r.input.weather};mode=r.mode;$('override').checked=r.mode==='simulated';fill();$('critical').value=r.assessment.critical_shortfall_ratio;$('adequate').value=r.assessment.adequate_margin_ratio;result(r);controls();save();};root.append(b);}for(const id of ['compareA','compareB']){const select=$(id),old=select.value;select.replaceChildren();for(const r of records){const o=el('option',new Date(r.created_at).toLocaleString('zh-CN')+' · '+(r.mode==='simulated'?'模拟':'真实')+' · '+risks[r.assessment.expected_loss_risk]);o.value=r.id;select.append(o);}if(records.some(r=>r.id===old))select.value=old;}if(records.length>1)$('compareB').value=records[1].id;}
function compare(){const a=records.find(r=>r.id===$('compareA').value),b=records.find(r=>r.id===$('compareB').value);if(!a||!b){notice('请先保存两次测试结果，再进行对比。',true);return;}const root=$('comparison');root.replaceChildren();root.append(el('p',`A：${a.mode==='simulated'?'模拟':'真实'}，B：${b.mode==='simulated'?'模拟':'真实'}；综合结果 ${risks[a.assessment.expected_loss_risk]} → ${risks[b.assessment.expected_loss_risk]}`));const rows=[];for(const [id,[part,key]] of Object.entries(map)){const av=a.input[part]?.[key]??null,bv=b.input[part]?.[key]??null;rows.push([$(id).parentElement.textContent.trim(),fmt(av),fmt(bv),av===bv?'未变化':'已变化']);}for(const [label,part,key] of [['组件型号','component','component_model'],['组件数据来源','component','source_name'],['历史气象来源','weather','source_name'],['经度','weather','longitude'],['纬度','weather','latitude'],['观测开始','weather','observation_start'],['观测结束','weather','observation_end']]){const av=a.input[part]?.[key]??'缺失',bv=b.input[part]?.[key]??'缺失';rows.push([label,av,bv,av===bv?'未变化':'已变化']);}rows.push(['余量充足阈值',a.assessment.adequate_margin_ratio,b.assessment.adequate_margin_ratio,a.assessment.adequate_margin_ratio===b.assessment.adequate_margin_ratio?'未变化':'已变化'],['能力不足阈值',a.assessment.critical_shortfall_ratio,b.assessment.critical_shortfall_ratio,a.assessment.critical_shortfall_ratio===b.assessment.critical_shortfall_ratio?'未变化':'已变化']);for(const r of a.comparisons){const other=b.comparisons.find(x=>x.hazard===r.hazard);rows.push([labels[r.hazard]+'判断',risks[r.risk],risks[other.risk],r.risk===other.risk?'未变化':'已变化']);}const t=table(['参数 / 结果','基准 A','对照 B','变化'],rows);for(const tr of t.querySelectorAll('tbody tr'))if(tr.lastChild.textContent==='已变化')tr.className='changed';const wrap=el('div','','tablewrap');wrap.append(t);root.append(wrap);}
function preset(){const which=$('scenario').value;const values={windCapacity:2400,hailCapacity:30,snowCapacity:5400,windEvent:30,hailEvent:20,snowEvent:3000};if(which==='shortfall')values.windCapacity=300;if(which==='missing'){values.hailEvent=null;values.snowEvent=null;}if(which==='boundary')values.windCapacity=0.613*30**2;if(which==='zero'){values.hailEvent=0;values.snowEvent=0;}mode='simulated';base={component:null,weather:null};$('model').value='模拟组件';$('longitude').value=0;$('latitude').value=0;$('start').value='';$('end').value='';for(const [id,value] of Object.entries(values))$(id).value=value??'';$('adequate').value=config.adequate_margin_ratio;$('critical').value=config.critical_shortfall_ratio;sources();controls();dirty();notice('已载入模拟场景；点击“运行评估”查看计算结果。');}
async function applyCase(c,context){if(!c)throw Error('当前案件尚无整单分析，请先运行整条链路。');base={component:c.component_profile||null,weather:c.weather_profile||null};original=structuredClone(base);mode='real';$('override').checked=false;fill();if(!base.component)$('model').value=c.project?.component_model||'';if(!base.weather){$('longitude').value=c.project?.longitude??'';$('latitude').value=c.project?.latitude??'';}$('critical').value=config.critical_shortfall_ratio;$('adequate').value=config.adequate_margin_ratio;current=null;$('results').replaceChildren(el('div','已带入参数，点击运行评估生成本次结果。','empty'));$('resultMeta').textContent='';$('dirty').hidden=true;sourceContext={title:context.title,run_label:context.run_label,return_url:context.return_url};PvWorkbench.contextBar(sourceContext);controls();notice('已带入 '+c.case_id+'。'+(context.stale?'原案件材料已更新；本次导入的是上一轮报告参数快照。':'')+(c.location_assessment?.status!=='verified'?'位置未完成核验，气象按候选位置解读。':'')+'缺失参数保持为空。');save();}
async function importCurrent(){const saved=await PvWorkbench.read('current');await applyCase(saved?.fullCase,{title:saved?.project?.project_name||'当前案件',run_label:'R'+(saved?.runNumber||1),return_url:'/evaluation?panel=process',stale:saved?.stale});}
PvWorkbench.beforeNavigate(async()=>{if(busy){notice('量化测试仍在运行，请等待完成后切换。');return false;}return save();});
$('real').onclick=()=>setMode('real');$('simulated').onclick=()=>setMode('simulated');$('preset').onclick=preset;$('override').onchange=()=>{controls();dirty();};
$('import').onclick=()=>task(importCurrent);
$('lookupComponent').onclick=()=>task(async()=>{const model=$('model').value.trim();if(!model)throw Error('请输入完整组件型号。');base.component=await api('/api/v1/risk/lab/component?model='+encodeURIComponent(model));original=structuredClone(base);for(const [id,[part,key]] of Object.entries(map))if(part==='component')$(id).value=base.component[key]??'';sources();dirty();notice('组件参数已取得；缺失抗灾值保持为空。');});
$('lookupWeather').onclick=()=>task(async()=>{const longitude=number('longitude'),latitude=number('latitude');if(longitude==null||latitude==null)throw Error('请输入 WGS84 经纬度，不能直接使用未经转换的其他坐标系。');const observation_start=$('start').value||null,observation_end=$('end').value||null;base.weather=await api('/api/v1/risk/lab/weather',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({longitude,latitude,observation_start,observation_end})});original=structuredClone(base);for(const [id,[part,key]] of Object.entries(map))if(part==='weather')$(id).value=base.weather[key]??'';$('start').value=base.weather.observation_start||'';$('end').value=base.weather.observation_end||'';sources();dirty();notice('气象查询完成；冰雹与雪荷载缺失时不会自动补值。');});
$('run').onclick=()=>task(async()=>{const payload=input();const r=await api('/api/v1/risk/lab/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});r.source_context=sourceContext;records.unshift(r);records=records.slice(0,30);result(r);histories();notice('评估完成，计算结果与输入快照已保存。');});
$('restore').onclick=()=>{base=structuredClone(original||{component:null,weather:null});mode='real';$('override').checked=false;fill();$('critical').value=config.critical_shortfall_ratio;$('adequate').value=config.adequate_margin_ratio;controls();dirty();notice('已恢复最近导入或查询数据。');};$('compare').onclick=compare;
$('export').onclick=()=>{if(!current)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({format:'pv-risk-lab-v1',...current},null,2)],{type:'application/json'}));a.href=url;a.download='风险测试-'+current.id+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const n of document.querySelectorAll('input'))if(n.id!=='override')n.addEventListener('input',dirty);
(async()=>{try{config=await api('/api/v1/risk/lab/config');$('adequate').value=config.adequate_margin_ratio;$('critical').value=config.critical_shortfall_ratio;const saved=JSON.parse(localStorage.getItem(storeKey)||'null');if(saved){sourceContext=saved.sourceContext||null;contextToken=saved.contextToken||null;base=saved.base||base;original=saved.original;records=saved.records||[];mode=saved.mode||'real';fill();for(const [id,value] of Object.entries(saved.draft||{}))if($(id)){if($(id).type==='checkbox')$(id).checked=value;else $(id).value=value;}if(saved.current)result(saved.current);}$('dirty').hidden=!(saved?.dirty&&current);histories();controls();PvWorkbench.contextBar(sourceContext);const token=new URL(location.href).searchParams.get('context'),incoming=await PvWorkbench.incoming('risk');if(incoming&&token!==contextToken){await applyCase(incoming.full_case,incoming);contextToken=token;save();}else if(saved)notice(mode==='simulated'?'已恢复模拟输入和测试记录；点击运行可重新计算。':'已恢复真实输入和测试记录。');}catch(e){notice('初始化失败：'+e.message,true);$('run').disabled=true;}})();
