(function(global){
  'use strict';
  let beforeLeave=async()=>true;
  const labels={case:'整单测试',history:'历史案例',image:'图片识别调试',risk:'抗灾量化调试'};
  function safeReturn(value){try{const u=new URL(value,location.origin);if(u.origin!==location.origin||u.pathname!=='/evaluation')return '/evaluation';return u.pathname+u.search;}catch{return '/evaluation';}}
  function db(){return new Promise((resolve,reject)=>{const q=indexedDB.open('pv-evaluation-replay',2);q.onupgradeneeded=()=>{for(const [name,options] of [['cases',{keyPath:'id'}],['workspace',undefined]])if(!q.result.objectStoreNames.contains(name))q.result.createObjectStore(name,options);};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
  async function read(key){const d=await db();try{return await new Promise((resolve,reject)=>{const q=d.transaction('workspace','readonly').objectStore('workspace').get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}finally{d.close();}}
  async function write(key,value){const d=await db();try{await new Promise((resolve,reject)=>{const tx=d.transaction('workspace','readwrite');tx.objectStore('workspace').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{d.close();}}
  async function handoff(kind,data){const token=crypto.randomUUID();const context={...data,kind,created_at:new Date().toISOString(),return_url:safeReturn(location.pathname+location.search)};if(data.work_id){const u=new URL(context.return_url,location.origin);u.searchParams.set('work',data.work_id);context.return_url=u.pathname+u.search;}await write('handoff:'+token,context);return (kind==='image'?'/vision-lab':'/risk-lab')+'?context='+encodeURIComponent(token);}
  async function incoming(kind){const token=new URL(location.href).searchParams.get('context');if(!token)return null;const value=await read('handoff:'+token);if(!value||value.kind!==kind)throw Error('调试来源不存在，请返回原案件重新进入。');return value;}
  function active(page){for(const a of document.querySelectorAll('.wb-nav [data-wb-page]')){if(a.dataset.wbPage===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}}
  function contextBar(context){let box=document.getElementById('wbContext');if(!box){box=document.createElement('div');box.id='wbContext';box.className='wb-context';document.querySelector('body>header')?.after(box);}box.replaceChildren();const text=document.createElement('div');text.textContent=context?'来源：'+(context.title||'当前案件')+' · '+(context.run_label||'未运行')+(context.file_name?' · '+context.file_name:context.item?.file?.name?' · '+context.item.file.name:''):'独立模块调试';const note=document.createElement('small');note.textContent='测试记录独立保存，不覆盖整单报告。';text.append(note);box.append(text);if(context){const a=document.createElement('a');a.className='wb-return';a.textContent='返回原案件';a.href=safeReturn(context.return_url);box.append(a);}return box;}
  async function navigate(href){if(await beforeLeave()===false)return;location.assign(href);}
  function init(page){document.body.classList.add('pv-workbench');const nav=document.createElement('nav');nav.className='wb-nav';nav.setAttribute('aria-label','工作台导航');const brand=document.createElement('strong');brand.textContent='光伏核保';nav.append(brand);for(const [name,paths] of [['业务测试',[['case','/evaluation'],['history','/evaluation?view=replay']]],['模块调试',[['image','/vision-lab'],['risk','/risk-lab']]]]){const small=document.createElement('small');small.textContent=name;nav.append(small);for(const [key,href] of paths){const a=document.createElement('a');a.href=href;a.textContent=labels[key];a.dataset.wbPage=key;nav.append(a);}}const help=document.createElement('a');help.href='/evaluation/report-preview';help.textContent='帮助 · 示例报告';help.className='wb-help';nav.append(help);document.body.prepend(nav);active(page);document.addEventListener('click',async e=>{const a=e.target.closest('.wb-nav a,.wb-context a,.wb-origin a');if(!a||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();try{await navigate(a.href);}catch(error){alert('保存失败，暂未离开当前页面：'+error.message);}});if(location.hostname==='127.0.0.1'){const message=document.createElement('div');message.className='wb-origin';message.append('当前是旧地址，历史材料保留在此入口。统一入口：');const a=document.createElement('a');a.href='http://localhost:8768'+location.pathname;a.textContent='localhost:8768（独立历史记录）';message.append(a);document.querySelector('body>header')?.after(message);}}
  global.PvWorkbench={init,active,read,write,handoff,incoming,contextBar,navigate,safeReturn,beforeNavigate:callback=>{beforeLeave=callback;}};
})(window);
